let identificacao = prompt("Informe o número de identificação do aluno")
let nota1 = parseFloat(prompt("Digite a primeira nota"))
let nota2 = parseFloat(prompt("Digite a segunda nota"))
let nota3 = parseFloat(prompt("Digite a terceira nota"))
let aproveitamento = (nota1 + nota2*2 + nota3*3)